version: '3.7'

x-defaults: &defaults
  build: .
  environment:
    TZ: Asia/Tokyo
    EDITOR: vi
    APP_PATH: /app
    RAILS_ENV: development
    POSTGRES_HOST: db
    POSTGRES_USERAME: postgres
    POSTGRES_PASSWORD:
  volumes:
    - .:/app
    - /app/tmp/cache
    - /app/tmp/pids
    - /app/.git
    - bundler-data:/usr/local/bundle

volumes:
  bundler-data:
  db-data:

services:
  rails:
    <<: *defaults
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    ports:
      - '3001:3001'
    tty: true
    stdin_open: true

  db:
    image: postgres:9.6
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  spring:
    <<: *defaults
    command: bundle exec spring server
      - db

#  guard:
#    <<: *defaults
#    command: bundle exec guard -i
#    depends_on:
#      - db
#      - cache
