# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"

gem "rails", "~> 6.0.0.rc1"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", ">= 1.4.2", require: false
gem "dotenv-rails", require: "dotenv/rails-now"
gem "graphql"
gem "jwt"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 3.11"
gem "rack-cors"

group :production do
  gem "heroku-deflater"
  gem "rails_12factor"
end

group :development, :test do
  gem "guard"
  gem "guard-rspec"
  gem "guard-rubocop"
  gem "guard-slimlint"

  gem "spring"
  gem "spring-commands-rspec"

  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "simplecov", require: false

  gem "rubocop", "0.62"
  gem "rubocop-rails_config"

  gem "better_errors"
  gem "binding_of_caller"
  gem "byebug"
  gem "pry"
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"

  gem "awesome_print"
  gem "tapp"
end

group :development do
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
